### ISSUE TITLE
Veterinarian Endpoints Security

### ISSUE THREAD

**Issue by 010Jay** [010Jay/Adp3Assignment3Group09#78]
Security should be implemented based on the requirement of the project and the specific entity in question.

**Comment by 010Jay** [comment]
Made changes in the Veterinarian entity, factory, service, and controller test for the Veterinarian to work correctly. You can update on your end to get the changes. 

Side Note: You should test to see if your implementation is working before committing.

**Comment by Nonhlahla** [comment]
Alright will do that.

**Comment by 010Jay** [comment]
Made a change in the Veterinarian controller, Please update.

**Comment by Nonhlahla** [comment]
Alright thanks
